### PR TITLE
Add support for outputReport, similar to eslint-loader

### PR DESCRIPTION
**Pull request by colinwkirk**
eslint-loader has support for outputReport, which is very useful. It also provides easy access to the filepath being examined by adding it to the message. With these you could use something like

module.exports.htmlhint.outputReport = {
        filePath: '../htmlhint.rpt',
        formatter: require(path.join(__dirname, 'mycustomformatter')),
    };

in your webpack.config.js to use your own custom formatter to output the results to a file.

### CODE REVIEW

**Comment by mattlewis92** [comment]
This looks really nice, thanks! Would you mind adding a test for the new functionality and documenting it in the readme (copy paste from eslint-loader is fine! 😄)

**Comment by colinwkirk** [comment]
Done. Not sure about the test, I only come to JS on occasion and am not terribly familiar with mocha.

**Comment by mattlewis92** [comment]
FYI you can run the linter locally via `npm run lint` :)

**Comment by colinwkirk** [comment]
But where's the fun in that when you can just test in production? ;)

**Comment by mattlewis92** [comment]
image
 
😃

**Comment by mattlewis92** [comment]
Amazing, thank you! I will review, merge and cut a new release tomorrow with this change 👍🏻

**Comment by colinwkirk** [comment]
Thanks.

**Comment by colinwkirk** [comment]
Added a small update, I'd forgotten to update the paths in the README from eslint to htmlhint. Only change in the last update...glad you hadn't merged yet. :)

**Comment by colinwkirk** [comment]
And last update for now, added the ability to use -[name] in the filePath for the output. Otherwise you'll only get one output file, no matter how many files are linted.

If you could get this reviewed and merged fairly soon, that would be really useful.

**Comment by mattlewis92** [comment]
Sorry didn't have time to review this today, I normally devote my Friday afternoons at work to open source so am 90% I will get it done then unless something urgent comes up 😀

**Comment by mattlewis92** [comment]
Published as 1.1.0, thanks for the contribution! 👍

**Pull request merged**
